# Copyright (C) 2026 Maxime P. DEMENTYEV
# SPDX-License-Identifier: GPL-3.0-only
# check_formatting per-repo configuration for this project's own source —
# an explicit, versioned declaration (mirrors check_rst's own
# .check_rst.toml convention: committed, tool-echoed, not auto-detected).
# Unknown keys are a hard error.

checks = ["python", "mypy", "rst"]

[python]
dirs = ["src", "docs/conf.py", "setup.py", "tools", "tests"]

[rst]
dir = "docs"
