#!/usr/bin/env python3.14
# Copyright (C) 2026 Maxime P. DEMENTYEV
# SPDX-License-Identifier: GPL-3.0-only
# Isolated ~/opt installation and launcher manager — check_formatting project
"""Install a checksummed wheel as a standalone utility under one prefix."""

from __future__ import annotations

import argparse
import ast
import hashlib
import os
import pathlib
import secrets
import shlex
import shutil
import subprocess
import sys
import tempfile
import zipfile
from email.parser import BytesParser
from email.policy import default

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
ENVIRONMENT_NAME = "check_formatting"
LAUNCHER_NAME = "check_formatting"
LAUNCHER_MARKER = "# Generated by check_formatting's tools/install_standalone.py."


class InstallError(RuntimeError):
    """A cleanly reportable standalone-installation failure."""


def _run(command: list[str], *, cwd: pathlib.Path | None = None) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        command,
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if result.returncode:
        details = "\n".join(part.rstrip() for part in (result.stdout, result.stderr) if part.strip())
        suffix = f"\n{details}" if details else ""
        raise InstallError(f"command failed with status {result.returncode}: {shlex.join(command)}{suffix}")
    return result


def _source_version() -> str:
    source = PROJECT_ROOT / "src" / "check_formatting" / "__init__.py"
    module = ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
    for statement in module.body:
        if not isinstance(statement, ast.Assign) or len(statement.targets) != 1:
            continue
        target = statement.targets[0]
        if (
            isinstance(target, ast.Name)
            and target.id == "__version__"
            and isinstance(statement.value, ast.Constant)
            and isinstance(statement.value.value, str)
        ):
            return statement.value.value
    raise InstallError(f"cannot find a literal __version__ assignment in {source}")


def _default_wheel() -> pathlib.Path:
    expected = PROJECT_ROOT / "dist" / f"check_formatting-{_source_version()}-py3-none-any.whl"
    if not expected.is_file():
        raise InstallError(f"default wheel does not exist; build it first: {expected}")
    return expected


def _absolute_prefix(raw_prefix: pathlib.Path) -> pathlib.Path:
    prefix = raw_prefix.expanduser().resolve()
    if prefix == pathlib.Path(prefix.anchor):
        raise InstallError(f"refusing filesystem-root installation prefix: {prefix}")
    return prefix


def _wheel_identity(wheel: pathlib.Path) -> tuple[str, str]:
    try:
        with zipfile.ZipFile(wheel) as archive:
            metadata_names = [name for name in archive.namelist() if name.endswith(".dist-info/METADATA")]
            if len(metadata_names) != 1:
                raise InstallError(f"wheel must contain exactly one METADATA file: {wheel}")
            metadata = BytesParser(policy=default).parsebytes(archive.read(metadata_names[0]))
    except (OSError, zipfile.BadZipFile) as exc:
        raise InstallError(f"cannot read wheel {wheel}: {exc}") from exc

    name = metadata.get("Name", "")
    version = metadata.get("Version", "")
    if name != "check-formatting" or not version:
        raise InstallError(f"wheel is not a check-formatting distribution: {wheel}")
    return name, version


def _verify_checksum(wheel: pathlib.Path) -> str:
    checksum_path = wheel.with_suffix(f"{wheel.suffix}.sha256")
    try:
        fields = checksum_path.read_text(encoding="utf-8").split()
    except OSError as exc:
        raise InstallError(f"cannot read wheel checksum {checksum_path}: {exc}") from exc
    if len(fields) != 2 or fields[1] != wheel.name or len(fields[0]) != 64:
        raise InstallError(f"invalid wheel checksum file: {checksum_path}")

    expected = fields[0].lower()
    actual = hashlib.sha256(wheel.read_bytes()).hexdigest()
    if not secrets.compare_digest(actual, expected):
        raise InstallError(f"SHA-256 mismatch for {wheel}: expected {expected}, got {actual}")
    return actual


def _uses_system_site_packages(environment: pathlib.Path) -> bool:
    configuration = environment / "pyvenv.cfg"
    if not configuration.is_file():
        raise InstallError(f"existing installation is not a virtual environment: {environment}")
    for line in configuration.read_text(encoding="utf-8").splitlines():
        key, separator, value = line.partition("=")
        if separator and key.strip() == "include-system-site-packages":
            return value.strip().lower() == "true"
    raise InstallError(f"virtual environment does not declare include-system-site-packages: {configuration}")


def _launcher_text(entry_point: pathlib.Path) -> str:
    return f'#!/bin/sh\n{LAUNCHER_MARKER}\nexec {shlex.quote(str(entry_point))} "$@"\n'


def _launcher_is_owned(launcher: pathlib.Path) -> bool:
    if not launcher.exists():
        return True
    try:
        return LAUNCHER_MARKER in launcher.read_text(encoding="utf-8").splitlines()
    except OSError, UnicodeError:
        return False


def _install_launcher(launcher: pathlib.Path, entry_point: pathlib.Path) -> None:
    launcher.parent.mkdir(mode=0o755, parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{launcher.name}.", dir=launcher.parent)
    temporary = pathlib.Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(_launcher_text(entry_point))
        temporary.chmod(0o755)
        os.replace(temporary, launcher)
    finally:
        temporary.unlink(missing_ok=True)


def _install(wheel_argument: pathlib.Path | None, prefix_argument: pathlib.Path, recreate: bool) -> None:
    prefix = _absolute_prefix(prefix_argument)
    wheel = (wheel_argument or _default_wheel()).expanduser().resolve()
    if not wheel.is_file():
        raise InstallError(f"wheel does not exist: {wheel}")
    _name, version = _wheel_identity(wheel)
    digest = _verify_checksum(wheel)

    environment = prefix / ENVIRONMENT_NAME
    launcher = prefix / "bin" / LAUNCHER_NAME
    entry_point = environment / "bin" / LAUNCHER_NAME
    if launcher.exists() and not _launcher_is_owned(launcher) and not recreate:
        raise InstallError(f"refusing to replace an unmanaged launcher without --recreate: {launcher}")

    environment_exists = environment.exists()
    if environment_exists and _uses_system_site_packages(environment) and not recreate:
        raise InstallError(
            f"existing environment exposes system site packages; use --recreate to migrate it: {environment}"
        )

    backup: pathlib.Path | None = None
    created_environment = False
    try:
        if environment_exists and recreate:
            backup = prefix / f".{ENVIRONMENT_NAME}.backup-{secrets.token_hex(8)}"
            os.replace(environment, backup)
            environment_exists = False

        if not environment_exists:
            prefix.mkdir(mode=0o755, parents=True, exist_ok=True)
            _run([sys.executable, "-m", "venv", str(environment)])
            created_environment = True

        if _uses_system_site_packages(environment):
            raise InstallError(f"standalone environment unexpectedly exposes system site packages: {environment}")

        python = environment / "bin" / "python"
        _run(
            [
                str(python),
                "-m",
                "pip",
                "install",
                "--force-reinstall",
                "--no-index",
                "--no-deps",
                str(wheel),
            ]
        )
        _run([str(python), "-m", "pip", "check"])
        observed = _run([str(entry_point), "--version"]).stdout.splitlines()
        expected = f"check_formatting {version}"
        if not observed or observed[0] != expected:
            raise InstallError(f"installed command reported the wrong version; expected {expected!r}")

        _install_launcher(launcher, entry_point)
    except InstallError, OSError:
        if backup is not None:
            if environment.exists():
                shutil.rmtree(environment)
            os.replace(backup, environment)
        elif created_environment and environment.exists():
            shutil.rmtree(environment)
        raise
    else:
        if backup is not None:
            shutil.rmtree(backup)

    print(f"installed check-formatting {version} in {environment}")
    print(f"verified SHA-256 {digest}")
    print(f"installed launcher {launcher}")


def _uninstall(prefix_argument: pathlib.Path) -> None:
    prefix = _absolute_prefix(prefix_argument)
    environment = prefix / ENVIRONMENT_NAME
    launcher = prefix / "bin" / LAUNCHER_NAME
    if environment.exists():
        _uses_system_site_packages(environment)
    if launcher.exists() and not _launcher_is_owned(launcher):
        raise InstallError(f"refusing to remove an unmanaged launcher: {launcher}")

    removed = False
    if launcher.exists():
        launcher.unlink()
        print(f"removed launcher {launcher}")
        removed = True
    if environment.exists():
        shutil.rmtree(environment)
        print(f"removed environment {environment}")
        removed = True
    if not removed:
        print("check-formatting standalone installation is absent")


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage an isolated check-formatting installation under ~/opt.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    install = subparsers.add_parser("install", help="verify and install a wheel plus its .sha256 sidecar")
    install.add_argument("wheel", nargs="?", type=pathlib.Path, help="wheel path; defaults to this checkout's version")
    install.add_argument("--prefix", type=pathlib.Path, default=pathlib.Path.home() / "opt")
    install.add_argument(
        "--recreate",
        action="store_true",
        help="replace an existing environment and any unmanaged launcher, with rollback on installation failure",
    )

    uninstall = subparsers.add_parser("uninstall", help="remove the owned environment and launcher")
    uninstall.add_argument("--prefix", type=pathlib.Path, default=pathlib.Path.home() / "opt")
    return parser


def main() -> int:
    arguments = _build_parser().parse_args()
    try:
        if arguments.command == "install":
            _install(arguments.wheel, arguments.prefix, arguments.recreate)
        else:
            _uninstall(arguments.prefix)
    except (InstallError, OSError) as exc:
        print(f"install_standalone: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
